apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secret
  namespace: jenkins
data:
  jenkins-admin-username: YWRtaW4=  # base64 encoded value for 'admin'
  jenkins-admin-password: YWRtaW4=  # base64 encoded value for 'admin'

