apiVersion: v1
kind: PersistentVolume
metadata:
  name: artifactory-data-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/artifactory

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifactory-data-pvc
  namespace: artifactory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: artifactory-db-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/artifactory-db

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifactory-db-pvc
  namespace: artifactory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: artifactory-volume-artifactory-0-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/artifactory-volume-artifactory-0

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifactory-volume-artifactory-0
  namespace: artifactory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-artifactory-postgresql-0-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/data-artifactory-postgresql-0

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-artifactory-postgresql-0
  namespace: artifactory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

