apiVersion: v1
kind: Service
metadata:
  name: artifactory
  namespace: jfrog
spec:
  selector:
    app: artifactory
  ports:
  - name: artifactory-http
    protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30106
  - name: artifactory-nginx
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30390
  type: NodePort


