apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifactory-postgresql
  namespace: jfrog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard

